### ISSUE TITLE
Implement sky offset Reduction class

### ISSUE THREAD

**Issue by danjampro** [AstroHuntsman/huntsman-drp#140]
- Measure sky from offset sky frames using a timedelta to select sky frames close enough to each science image
- Perform ISR, image characterisation on sky frames to get backgrounds (LSST takes care of source masking)
- Median combine sky backgrounds without co-aligning them to get "master" background for that particular time 
- Perform ISR, image characterisation and image calibration on science image using master background without re-estimating background at each step

**Comment by danjampro** [comment]
Might need to override source detection settings in image characterisation of sky fields to perform deeper object detection than usual.

Will also need to think about other background subtraction config options.

**Comment by lspitler** [comment]
Looks good @danjampro . 

Only suggestion is to consider a 2-pass sky subtraction, which is common in near-IR observations where sky subtraction is really important due to strong time variations. See e.g. https://iopscience.iop.org/article/10.1088/0004-637X/735/2/86#apj393402s3

Idea is to do a second sky subtraction after the first as  object masking will depend on how good the sky subtraction. In our case, perhaps this is more important for extended sources like galaxies, including the main target.

~Lee
